// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ClassLibrary1.Models;

public partial class CLIENTE
{
    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string apellido { get; set; }

    public string contrasenia { get; set; }

    public string dni { get; set; }

    public int? id_direccion { get; set; }

    public string telefono { get; set; }

    public string nro_cuit { get; set; }

    public string e_mail { get; set; }

    public int? id_iva { get; set; }

    public int? id_tipo_dni { get; set; }
    [JsonIgnore]
    public virtual ICollection<FACTURA> FACTURAs { get; set; } = new List<FACTURA>();
    [JsonIgnore]
    public virtual DIRECCIONE id_direccionNavigation { get; set; }
    [JsonIgnore]
    public virtual IVA id_ivaNavigation { get; set; }
    [JsonIgnore]
    public virtual TIPO_DNI id_tipo_dniNavigation { get; set; }
}