// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models;

public partial class DIRECCIONE
{
    public int id_direccion { get; set; }

    public string descripcion { get; set; }

    public int? id_barrio { get; set; }

    public virtual ICollection<CLIENTE> CLIENTEs { get; set; } = new List<CLIENTE>();

    public virtual BARRIO id_barrioNavigation { get; set; }
}