// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ClassLibrary1.Models;

public partial class FACTURA
{
    public int id_factura { get; set; }

    public DateTime? fecha { get; set; }

    public int? id_cliente { get; set; }

    public int? id_tipo_factura { get; set; }

    public virtual ICollection<DETALLE_FACTURA> DETALLE_FACTURAs { get; set; } = new List<DETALLE_FACTURA>();

    [JsonIgnore]
    public virtual CLIENTE id_clienteNavigation { get; set; }
    [JsonIgnore]
    public virtual TIPO_FACTURA id_tipo_facturaNavigation { get; set; }
}