// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models;

public partial class IVA
{
    public int id_iva { get; set; }

    public decimal? descripcion { get; set; }

    public virtual ICollection<CLIENTE> CLIENTEs { get; set; } = new List<CLIENTE>();
}