// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models;

public partial class LOCALIDADE
{
    public int id_localidad { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<BARRIO> BARRIOs { get; set; } = new List<BARRIO>();
}