// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ClassLibrary1.Models;

public partial class TIPO_DNI
{
    public int id_tipo_dni { get; set; }

    public string descripcion { get; set; }

    public virtual ICollection<CLIENTE> CLIENTEs { get; set; } = new List<CLIENTE>();
}